# Generated by Django 4.2 on 2024-01-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='review',
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trainerprofile'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.job'),
        ),
    ]
