# Generated by Django 4.2 on 2024-02-02 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_time_job_created_at_remove_job_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated', to='app.trainerprofile'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater', to='app.userprofile'),
        ),
    ]
