# Generated by Django 4.2 on 2024-02-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_budget_alter_rating_rated_alter_rating_rater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('inprocess', 'Inprocess')], default='inprocess', max_length=100),
        ),
    ]
