# Generated by Django 4.2 on 2024-02-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='code',
            field=models.CharField(max_length=12),
        ),
    ]
