# Generated by Django 4.2 on 2024-02-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_topup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='used_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topup',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
