# Generated by Django 4.2 on 2024-02-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_rating_bid_remove_rating_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerprofile',
            name='number_of_jobs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainerprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
