# Generated by Django 4.2 on 2024-02-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bid_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
    ]
